name: fire_inspection_app
description: Fire alarm inspection and inventory management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Barcode scanning
  mobile_scanner: ^3.5.2
  
  # Camera & photos
  camera: ^0.10.5
  image_picker: ^1.0.4
  
  # GPS & EXIF
  geolocator: ^10.1.0
  exif: ^3.3.0
  
  # Networking
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  
  # State management
  provider: ^6.1.1
  
  # Storage & preferences
  shared_preferences: ^2.2.2
  
  # Utilities
  uuid: ^4.2.1
  path_provider: ^2.1.1
  intl: ^0.20.0
  
  # UI enhancements
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  
  # PDF generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Permission handling
  permission_handler: ^11.1.0

  # Image processing
  image: ^4.0.17

  # Sharing files
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true